#!/bin/bash

set -euo pipefail

docker build -t netsuite_integration -f Dockerfile .
docker tag -f netsuite_integration:latest 914794084459.dkr.ecr.us-east-1.amazonaws.com/netsuite_integration:latest
docker push 914794084459.dkr.ecr.us-east-1.amazonaws.com/netsuite_integration:latest
